apps:
  - name: management-discord-bot
    environment: production
    codebase: management-discord-bot
    replicaCount: 1
    container:
      image:
        repository: osuakatsuki/management-discord-bot
        tag: latest
      port: 80
      # readinessProbe:
      #   httpGet:
      #     path: /_health
      #     port: 80
      #   initialDelaySeconds: 10
      #   periodSeconds: 10
      #   timeoutSeconds: 1
      #   successThreshold: 1
      #   failureThreshold: 3
      resources:
        limits:
          cpu: 300m
          memory: 1Gi
        requests:
          cpu: 150m
          memory: 700Mi
      env:
        - name: APP_COMPONENT
          value: bot
      imagePullSecrets:
        - name: osuakatsuki-registry-secret
