version: "3.3"

services:
  ## shared/managed services

  postgres:
    image: postgres:13
    environment:
      # NOTE: running with the assumption that local dev will not have read replication
      # (meaning that the read & write dbs will be the same)
      POSTGRES_PASSWORD: ${WRITE_DB_PASS}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432

  selenium:
    image: selenium/standalone-chrome:latest
    volumes:
      - ./data:/bot-data
    ports:
      - 4444:4444

  ## application services
  management-discord-bot:
    image: management-discord-bot:latest
    environment:
      - APP_ENV=${APP_ENV}
      - APP_COMPONENT=${APP_COMPONENT}
      - PULL_SECRETS_FROM_VAULT=${PULL_SECRETS_FROM_VAULT}
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
      - DATA_DIR=${DATA_DIR}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - SELENIUM_DRIVER_URL=${SELENIUM_DRIVER_URL}
      - READ_DB_SCHEME=${READ_DB_SCHEME}
      - READ_DB_HOST=${READ_DB_HOST}
      - READ_DB_PORT=${READ_DB_PORT}
      - READ_DB_USER=${READ_DB_USER}
      - READ_DB_PASS=${READ_DB_PASS}
      - READ_DB_NAME=${READ_DB_NAME}
      - READ_DB_USE_SSL=${READ_DB_USE_SSL}
      - READ_DB_CA_CERTIFICATE=${READ_DB_CA_CERTIFICATE}
      - INITIALLY_AVAILABLE_READ_DB=${INITIALLY_AVAILABLE_READ_DB}
      - WRITE_DB_SCHEME=${WRITE_DB_SCHEME}
      - WRITE_DB_HOST=${WRITE_DB_HOST}
      - WRITE_DB_PORT=${WRITE_DB_PORT}
      - WRITE_DB_USER=${WRITE_DB_USER}
      - WRITE_DB_PASS=${WRITE_DB_PASS}
      - WRITE_DB_NAME=${WRITE_DB_NAME}
      - WRITE_DB_USE_SSL=${WRITE_DB_USE_SSL}
      - WRITE_DB_CA_CERTIFICATE=${WRITE_DB_CA_CERTIFICATE}
      - INITIALLY_AVAILABLE_WRITE_DB=${INITIALLY_AVAILABLE_WRITE_DB}
      - DB_POOL_MIN_SIZE=${DB_POOL_MIN_SIZE}
      - DB_POOL_MAX_SIZE=${DB_POOL_MAX_SIZE}
      - SERVICE_READINESS_TIMEOUT=${SERVICE_READINESS_TIMEOUT}
      - SCOREWATCH_CHANNEL_ID=${SCOREWATCH_CHANNEL_ID}
      - ADMIN_SCOREWATCH_CHANNEL_ID=${ADMIN_SCOREWATCH_CHANNEL_ID}
      - REPORT_CHANNEL_ID=${REPORT_CHANNEL_ID}
      - ADMIN_REPORT_CHANNEL_ID=${ADMIN_REPORT_CHANNEL_ID}
      - AKATSUKI_GUILD_ID=${AKATSUKI_GUILD_ID}
      - AKATSUKI_SCOREWATCH_ROLE_ID=${AKATSUKI_SCOREWATCH_ROLE_ID}
    volumes:
      - .:/srv/root
      - ./scripts:/scripts
    depends_on:
      - selenium
      - postgres
